### ISSUE TITLE
It work on local but not on production

### ISSUE THREAD

**Issue by donmbelembe** [davidpiesse/nova-phpinfo#4]
Can't understand this, it works in local but when i push on the server it doesn't show the link.
my local environment is on windows and production is debian

**Comment by davidpiesse** [comment]
Hi @donmbelembe ,
So locally you see the left hand side menu tab; but in production it is gone?!
Could your dependencies require it only in 'dev-depenedencies'?

Any more info would be helpful in trying to help you out.

D

**Comment by donmbelembe** [comment]
It seems nova couldn't detect the change directly, or maybe cache (but i tried to delete cache several times without success).
It worked only when i made a change on one of my nova resources
